SELECT * FROM odontologo;
SELECT * FROM agenda;
SELECT * FROM paciente;
SELECT * FROM turno;
SELECT * FROM tipoturno;
SELECT * FROM turnosdisponibles;
INSERT INTO odontologo VALUES (33421123,'Jorge','Videla');
INSERT INTO odontologo VALUES (41155173,'Lautaro','Martin');
INSERT INTO odontologo VALUES (12333124,'Rafael','Tisera');
INSERT INTO odontologo VALUES (43212312,'Carlos','Acosta');
INSERT INTO odontologo VALUES (56787767,'Mariel','Ojeda');
INSERT INTO agenda VALUES (5,12345,'2019-05-1','2019-05-10','09:00','18:00');
INSERT INTO turno VALUES(3,false,3,28153673,'17:00','2019-05-21');
INSERT INTO paciente VALUES(1,'Cosme','Fulanito');
INSERT INTO paciente va
CREATE TABLE agenda (
	ID_DIA varchar,
	ID_MES varchar,
	HORA_ENTRADA time without time zone,
	HORA_SALIDA time without time zone,
	ID_DNI integer,
	PRIMARY KEY(ID_DIA, ID_MES)
);
ALTER TABLE agenda
ADD CONSTRAINT CONSTRAINT_DNI FOREIGN KEY(ID_DNI) REFERENCES odontologo(ID_DNI);
CREATE TABLE odontologo (
	ID_DNI INTEGER PRIMARY KEY,
	NOMBRE VARCHAR,
	APELLIDO VARCHAR
);
CREATE TABLE paciente (
	PACIENTE_DNI INTEGER PRIMARY KEY,
	NOMBRE VARCHAR,
	APELLIDO VARCHAR
);
drop table tipoturno;
CREATE TABLE tipoturno(
	TRATAMIENTO VARCHAR,
	TIPO_TURNO INTEGER,
	PRECIO INTEGER,
	PRIMARY KEY(TRATAMIENTO,PRECIO)
);
ALTER TABLE tipoturno
ADD CONSTRAINT CONSTRA_tturno FOREIGN KEY(TIPO_TURNO) REFERENCES turno(TIPO_TURNO);
ALTER TABLE tipoturno
ADD CONSTRAINT CONSTRA_unique2 
UNIQUE (PRECIO);
CREATE TABLE turno(
	TIPO_TURNO INTEGER PRIMARY KEY,
	TRATAMIENTO VARCHAR REFERENCES tipoturno(TRATAMIENTO),
	PRECIO INTEGER REFERENCES tipoturno(PRECIO),
	DNI_ODONT INTEGER REFERENCES odontologo(ID_DNI),
	DNI_PAC INTEGER REFERENCES paciente(PACIENTE_DNI)
);
CREATE TABLE turnosdisponibles(
	FECHA timestamp without time zone,
	HORA time without time zone,
	IDDNI INTEGER REFERENCES odontologo(ID_DNI),
	ESTADO boolean
);